print("There.")
print("Technicals, nine o'clock.")
print("Oh, shit! Did you see that?")
print("Chief, we got unarmed civilians")
print("getting shot down here at nine o'clock.")
print("I got it, Matt.")
print("I don't think we can touch this.")
print("Command, Super 64...")
print("...we got militia shooting civilians")
print("at the food distribution centre.")
print("Request permission to engage.")
print("Super 64, are you taking fire? Over.")
print("Negative, command.")
print("U.N.'s jurisdiction, 64")
print("We cannot intervene.")
print("-Return to base. Over.")
print("-Roger.")
print("Leaving")
print("General Garrison?")
print("No, thanks. I got one.")
print("But these are Cuban.")
print("Bolivar Belicoso.")
print("So is this.")
print("Miami, my friend, is not Cuba.")
print("I see not catching Aidid")
print("is becoming a routine.")
print("We weren't trying to catch Aidid.")
print("We were trying to catch you.")
print("Me?")
print("But am I that important?")
print("I hardly think so.")
print("-You're just a businessman.")
print("-Trying to make a living.")
print("Yeah. Selling guns to Aidid's militia.")
print("You've been here, what?")
print("Six weeks?")
print("Six weeks")
print("you are trying to catch the general.")
print("You put up reward posters.")
print("$25,000. What is this?")
print("Gunfight at the K.O. Corral?")
print("It's the O.K. Corral.")
print("Do you think bringing me in")
print("will make him suddenly come to you?")
print("Make him more agreeable?")
print("You know where he sleeps.")
print("You pay for his beds, much less his militia.")
print("We're not leaving Somalia till we find him.")
print("And we will find him.")
print("Don't think because I grew up")
print("without running water...")
print("...I am simple, General.")
print("I do know something about history.")
print("See all this? It's simply shaping tomorrow.")
print("A tomorrow without a lot")
print("of Arkansas white boys' ideas in it.")
print("Well, I wouldn't know about that.")
print("I'm from Texas.")
print("Mr. Garrison,")
print("I think you shouldn't have come here.")
print("This is civil war.")
print("This is our war.")
print("Not yours.")
print("That's not a war, Mr. Atto.")
print("That's genocide.")
print("Now, you enjoy that tea, you hear?")
print("How'd he strike you?")
print("Urbane, sophisticated, cruel.")
print("Yeah, he's a good catch.")
print("It'll take time, but Aidid will feel the loss.")
print("I'm not sure time is something we got")
print("in great supply.")
print("This isn't Iraq, you know.")
print("Much more complicated than that.")
print("Boss, most of Washington might disagree.")
print("They've been calling for situation reports")
print("every morning this week.")
print("Well, tell them the situation is fragile.")
print("Ladies and gentlemen,")
print("I'm Cliff Elvis Wolcott.")
print("I'll be your pilot today.")
print("Federal regulations designate this")
print("a non-smoking Black Hawk helicopter.")
print("Those in Mogadishu frequent flyer program")
print("will earn 100 free credits.")
print("And as always, the air sickness bags")
print("are in the seatback in front of you.")
print("Number one indications are good, Cliff.")
print("and I'll spank you, Nightstalker.")
print("Yeah, promises.")
print("That's a nice beach down there.")
print("How's the water?")
print("Yeah, it's nice and warm.")
print("And it's loaded with sharks.")
print("-Name.")
print("-Todd.")
print("-Last name.")
print("-Blackburn.")
print("First name, Todd.")
print("-So, what's it like?")
print("-What's what like?")
print("Mogadishu. The fighting.")
print("-Serial number.")
print("-72163427.")
print("Firstly, it's the Mog or simply Mog.")
print("No one calls it Mogadishu here.")
print("Secondly, I wouldn't know")
print("about the fighting, so don't ask.")
print("Why not?")
print("Didn't I just say, Don't ask? ")
print("You look like you're about 12,")
print("so let me explain something to you.")
print("I have a rare and mysterious skill")
print("that precludes me from doing missions.")
print("Typing.")
print("-Can you type?")